# Example Software AG Products containers building pipeline
# Fork and specialize according to need

trigger:
- main

pool:
  name: WmDevOpsTutorialAgentsPool
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-gen2:latest

jobs:

- job: msr1011leanOriginalApproach
  displayName: 'MSR 10.11 lean original Approach'
  steps:

    # Some variables must be propagated accross steps
    - script: |
        echo 'Computing initial local variables for job'

        JOB_SUIF_TEMPLATE="MSR/1011/lean"
        echo "##vso[task.setvariable variable=JOB_SUIF_TEMPLATE;]${JOB_SUIF_TEMPLATE}"

        JOB_DATE=$(date +%y-%m-%d)
        echo "##vso[task.setvariable variable=JOB_DATE;]${JOB_DATE}"

        JOB_DATETIME=$(date +%y-%m-%d'T'%H.%M.%S_%3N)
        echo "##vso[task.setvariable variable=JOB_DATETIME;]${JOB_DATETIME}"
      displayName: 'Job Locals'

    # grant execution permissions to the repository scripts
    - script: chmod u+x ./*.sh
      displayName: "Grant shell execution permissions"
    
    - script: |
        export JOB_SUIF_TAG='v.0.4.0'
        ./01.getSUIF.sh
      displayName: "Get SUIF commons"
