# Example Software AG Products containers building pipeline
# Fork and specialize according to need

trigger:
- main

pool:
  name: WmDevOpsTutorialAgentsPool
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-gen2:latest

variables:
  - group: ContainerImagesBuild.Options

jobs:

- job: msr1011leanOriginalApproach
  displayName: 'MSR 10.11 lean original approach'
  steps:

    # grant execution permissions to the repository scripts
    - script: find . -type f -name "*.sh" -exec chmod u+x "{}" \;
      displayName: "Grant shell execution permissions"

    # Some variables must be propagated accross steps
    - script: |
        export JOB_SUIF_TAG=$(SUIF_TAG)
        export SUIF_FIXES_DATE_TAG=$(SUIF_FIXES_DATE_TAG)
        export MY_AZ_ACR_URL=$(MY_AZ_ACR_URL)
        ./00.setJobInitialVariables.sh
      displayName: 'Job Locals'
    
    - script: ./01.getSUIF.sh
      displayName: "Get SUIF commons"

    # get SA share secrets
    - task: DownloadSecureFile@1
      name: SASecureInfo
      displayName: 'Download secure information for images share'
      inputs: 
        secureFile: 'sa.share.secrets.sh'

    # mount SA share
    - script: ./02.mountImagesShare.sh
      displayName: 'Mount images share'

    # update ubuntu machine
    - script: ./03.prepareAgentMachine.sh
      displayName: 'System software preparation'

    # assure installation binaries
    - script: ./04.assureInstallBinaries.sh
      displayName: 'Assure installation binaries'
    
    # Boostrap Update Manager
    - script: ./05.installSUM.sh
      displayName: 'Install SUM'

    # MSR license is required at build time
    - task: DownloadSecureFile@1
      name: msrLicense
      displayName: 'Download MSR license'
      inputs:
        secureFile: 'msr-license.xml'

    # Save audit on share 
    # HINT: ou should use this step only for debug purposes
    # HINT: without this step the mount may be readonly
    - script: ./11.saveAudit.sh
      displayName: 'Save Audit on Share'
      condition: always()

    # Setup MSR 10.11 lean
    - script: ./msr/1011/lean/06.install.sh
      displayName: 'Install MSR'

    # Containerize
    - script: ./msr/1011/lean/original/07.containerize.sh
      displayName: 'Containerize MSR'

    # umount SA share
    - script: ./12.unmountShare.sh
      displayName: 'Unmount images share'
      condition: always()